#!/bin/sh
cd docking/output_models/GPX_Neisseria-meningitidis
cwd=$(pwd)
cd ../../../grid/output_models
gd=$(pwd)
cd $cwd
sed -i "s@GRID_PATH@$gd@" GPX_Neisseria-meningitidis_GSH.in 
"${SCHRODINGER}/glide" GPX_Neisseria-meningitidis_GSH.in -OVERWRITE -adjust -HOST localhost:1 -TMPLAUNCHDIR -WAIT
cd ../../..
