#!/bin/sh
cd docking/output_models/GPX_Bacillus-subtilis
cwd=$(pwd)
cd ../../../grid/output_models
gd=$(pwd)
cd $cwd
sed -i "s@GRID_PATH@$gd@" GPX_Bacillus-subtilis_GSH.in 
"${SCHRODINGER}/glide" GPX_Bacillus-subtilis_GSH.in -OVERWRITE -adjust -HOST localhost:1 -TMPLAUNCHDIR -WAIT
cd ../../..
