#!/bin/sh
cd prepwizard/output_models/GPX_Staphylococcus-aureus
"${SCHRODINGER}/utilities/prepwizard" ../../input_models/GPX_Staphylococcus-aureus.pdb GPX_Staphylococcus-aureus.pdb -fillsidechains -disulfides -propka_pH 7.0 -f 2005 -rmsd 0.3 -JOBNAME GPX_Staphylococcus-aureus -HOST localhost:1 -WAIT
cd ../../..
