#!/bin/sh
cd docking/output_models/GPX_Staphylococcus-aureus
cwd=$(pwd)
cd ../../../grid/output_models
gd=$(pwd)
cd $cwd
sed -i "s@GRID_PATH@$gd@" GPX_Staphylococcus-aureus_GSH.in 
"${SCHRODINGER}/glide" GPX_Staphylococcus-aureus_GSH.in -OVERWRITE -adjust -HOST localhost:1 -TMPLAUNCHDIR -WAIT
cd ../../..
